### ISSUE TITLE
Convert data into TFRecords

### ISSUE THREAD

**Issue by tobegit3hub** [chenghuige/tensorflow-example#1]
Thanks for the good examples with sparse data. It would be great if you convert sparse data into TFRecords so that we can read it with QueueRunner and Coordinator.

**Comment by salman1993** [comment]
Hello, 

Thanks a lot for your code. I have been using the melt.py file to read SVM Lib file (with minor adjustments). I also have a sparse TF-IDF feature matrix. The problem with this repo is that the mini batch produced is not randomized at each epoch. So I started looking online and found your blog...
http://www.cnblogs.com/rocketfan/p/5765979.html

I tried to translate your blog to English and read it. It seems like you convert it to TFRecord so that can be used to easily generate random mini batches. If that is the case, can you pls share your code with me? I want to learn more and I also need it for a text classification task. It will be a lot of help. Also, it would be great if you could tell me how to contact you.

Thanks, 
Salman

**Comment by chenghuige** [comment]
@tobegit3hub and @salman1993  sorry for late response, Ok , I will share that code  using tfrrecords soon:)

**Comment by tobegit3hub** [comment]
I have implemented the similar script to read and convert the libsvm files. You can also refer to this and any feedback is welcome https://github.com/tobegit3hub/deep_recommend_system/tree/master/data

**Comment by chenghuige** [comment]
@tobegit3hub  glad to see you have solved this problem:)  
deep_recommend_system is great work! 
Anyway I will post  my solution of one simple text classification example using tf-record.
@salman1993  as this work has been done, closing this issue.  
If you use my work and find any problem just reopen this.
